version: "~> 1.0"
git:
  depth: 1
  quiet: true
language: java
jdk:
  - openjdk17
branches:
  only:
    - develop
    - support/4.1.x
    - support/4.0.x
    - master
cache:
  directories:
    - "$HOME/.m2"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c "mvn deploy --settings .travis-settings.xml"; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install"; fi
env:
  global:
   - secure: "gh7NWFk3mwTQ1U5QIxBmMqfRJ7VseIjZmAMpadLNLOZAjCMxa3Z2XpdBnAA6dELEiSmveB2bQfR6fcQiVnvXYOWkIBchLfTqI2tX00WBg7NL9oEZXZkTk7Q9CqMc1wQzShaslGJMciLPpDkffxUoL+XEHhD1Q7jMpVi0YYFrGCGgYCPL03dReh/v+8Mq8GWnDiacnzNRMAAGfmdFrvrJsWlvwCYXlfql3dejdo1pY60iDsPonAIQkdXf3OreWfdPh2QyhjUfWD1H8gi5G1/2XCyL5Ul+wVBLWiEd3eYQV4qYd6M+XeGmeJC87nkB581m46rS4BJV7zoYFm1r6cHRRSxU46arFXO4LYu22xC84XKR/+Jf7QsewClZr1HcgBDob4E5lfKGq8eTP5uKwW1mOyt9igV50BoVNsxRqXGhblEJRwhGUi41fNUtweH/l6uxdWuRXdgCwW6rtPfY245rH+XGzkWfHOBbfpF0ULTzUqmo7f0K+uS6/qZNFj+nMpDKUwH9d51bsllWWYh/ZkQi3vQcsYhycS0KvYZVoy127IE4fCYhHCdEZJFjjtw1jCFHMvx9f3u0Sig1LNHzi88Svm7x5ZkruffQ1CctWTOsuS5ws9NXq6W27i7jHmx282hLY0/8ROc1AWDRrSyFDLQm/KCrvY4tIOO+X269BUU6r40="
   - secure: "FTTI7onHY1lS1UCu7l/PVO/Y1vtmI4Pb840E7RZcP6vN4Et26cyhB6Eeo1/CNS2Neuwz/3Y6rz5u6eb6r24h571bQXk3mqEDvvyHeQpiDyNMWMo8PuaYgS6NmtrSlqtwfaf/SGvDG732jWZnDTAnBuPbtzZp5OYuegC7JWiw2dQs5P0cD18/R7cxHqjvtsHemrgND7lH0wZAzesRA4Y1HUE3dt7Rrq99Dgo+i8hqlwc3eDDqFQcFLBCZiLekDYxkiKLb5EK09NGZT5yhvrCF62h2+ORVZ/QVwxTn8KsLCyM/oYOfRaxhkaOTGGfDJyEGOlv+6e0ugUardOR5okbh0334eLxHopd8U4JfrpZ0TUi60ZTK+9yCRizfqxszqE9zqFHssoRle3l9Y5CiivOX+7CQiOIIl3H8ahfw6u84sGb781LBbov/RkF7/m9AYTH0r4DqSZe9+DGU4Y8rOzwZO+oUaenFV9arP+N1TEm7eMIII1J39XjOOlkFPQQcDajzTvRk3QHGuYbPscq65Z2Otyw1OP2xyM75YXWHIoZWEYQhmg9KcV+PfIBGGfw2cmv/oD0CSvVmr9K+V8N9yQHoAmcZWf/3lkUeY6LHLAgXb2FD0qgHvJKIX4jMpKm2t9Hh6ZnaVX74JhFshAVkQiWUH/VFtXsQzqmxkTj+wWVUc/4="

