version: ~> 1.0
git:
  depth: 1
  quiet: true
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
cache:
  directories:
  - "$HOME/.m2"
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then bash -c  "mvn deploy --settings
  .travis-settings.xml";  fi
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then bash -c "mvn clean install" ;fi
env:
  global:
  - secure: EZyNy+o/Y79WKvCyjo/phmw0uO3qf4JPB2UZOUK/2bZvvZUcp096URw5IL7Hg+H7OnGGkhq6nA2LIIQ09etrm+7MA6ARnXuUE5bC64iDn//qoVTOYV62RM0J6NWYx2JcYeYrUAfkUK8LYNEg/cwFLy2EcJSUqCZvlq4JpzJjvTYMcG9JyYimkP7xZmZ43HHcF5an9yHYbo+7+SKg2A/Wji1LRDzCFhT45ain1l8dNZcu3Q1OMkbzNp4TncBIX367peKDL5McGWKYr5cO/vchKuJR1GlbjG4AA9+Ixfh/qPzvNxfrohfMFVUYVfE1+6NuDxz4utveg8juJmPgsfCASJc9hnC9NffW/c3CutQmq1M0Jn++efTog+75w6kpgyjupC0Yn/zwOE/upbPosDSTTbWXxTxp0/4mRXjZ7dzPeW8VtwRlV1AnXhrDDpFRQQe8I5pESRipJNKRBAiR/bJfO8J+v8hSIhUH5eRcsSeSufrsnIQGXbcVQVOqCqKsTvpE3ZmLFKqqjeMivewtsH3Pfdij8LJIvkwCBHmbazFEkvKHjsDEnM7NwGtGIJxSig0XLKajOAKSBLcXzh4V/aquL/fSnENVTsigidOrTDj0b0SSof/JKBxtAckF7KAV/Q7su6hP0r5KIPKvThBfmJE9egZq18rHb96lHviB49QEVzM=
  - secure: ZP2+DHgXF+WU6JrDfnTJcNvabblMvagpjP2Sft3Gj/QM1dO6BsD4fdy96iMBbS235elW/wQ7BP8lKPRyjZUkxJ8/nH75JxbaEeVPqqsaRWa2+75X4TccJshu5zMgZVyoZf4dGlv2q4Gtba6WaPvXLeXPdAc15aHwXzsAsGaVIJJT3PAoQKaxxZPGiDaP2AHHMqCGgIK3BVfwC+ruHIUvIwo7d735YJUK4oFPc1jJDlblMRSiOzsQqLEIFz5+iKZtd58dweZknHWKRZnPppz4hXMTP4IDqTmo30j4qtm5v12P6C4OmPe8CTUyEVSk9J1IJeOj0uWdXi5J14dfJFKu/Vj+MRTIPnmaMwBjiPTTKGDNKz/KJC4PF1dxGzgTl0GbVcjqmkjCSD9Nstv0OnGhzGD64kbrAk7UM2b9ibxVVRGyxAg2xLYXPGKxyRmSqvBTsIoaON4D2i8LNImefHoN8rsnoIhxzRaVmy5U2iuTBsdEYIYnZ59yADZxhcyRsYKJuGWOBPRERgTl8/ACHjxBk0K8PoagQkC7N9nV6vgsfQpYUUAqfqLLKc1ZI1L4+HGuNfC8myYCBqpuwG5VgILNoFww15E4h13c2D6rDuZw7W8PwNIQXpdITs2Lx89FNqsZy/b+o/zmVkKHq3k3Al7N+b6gOGyUNXPXlbyGetSfZCY=
